apiVersion: batch/v1
kind: Job
metadata:
  name: sdv-runtime-pull
spec:
  # Add backoff limit to prevent infinite retries
  backoffLimit: 3
  # Set active deadline to prevent hanging jobs
  activeDeadlineSeconds: 600
  template:
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: xip
      restartPolicy: Never
      containers:
      - name: sdv-runtime-pull
        image: ${DOCKER_HUB_NAMESPACE}/sdv-runtime:dc1f218806aa00e1a99df23c7e2ed387b0c6da70
        imagePullPolicy: Always
        command: ["true"]
        # Add resource limits to prevent resource issues
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
