apiVersion: apps/v1
kind: Deployment
metadata:
  name: dk-ivi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dk-ivi
  template:
    metadata:
      labels:
        app: dk-ivi
    spec:
      nodeSelector:
        kubernetes.io/hostname: xip
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      volumes:
      - name: dk-home
        hostPath: 
          path: /home/sdv-orin/.dk
          type: DirectoryOrCreate
      - name: x11-unix
        hostPath: 
          path: /tmp/.X11-unix
          type: Directory
      - name: dri
        hostPath: { path: /dev/dri }
      - name: kubectl-binary
        hostPath:
          path: /usr/local/bin/kubectl
          type: File
      - name: kube-config
        hostPath:
          path: /home/sdv-orin/.kube/config
          type: File
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: docker-binary
        hostPath:
          path: /usr/bin/docker
          type: File
      containers:
      - name: dk-ivi
        image: docker.io/library/dk_ivi:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          privileged: false
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_ADMIN
            - SYS_ADMIN
        env:
        - name: DISPLAY
          value: ":0"
        - name: XDG_RUNTIME_DIR
          value: "/run/user/1000"
        - name: QT_QUICK_BACKEND
          value: "software"
        - name: DKCODE
          value: "dreamKIT"
        - name: DK_USER
          value: "sdv-orin"
        - name: DK_VIP
          value: ""
        - name: DK_DOCKER_HUB_NAMESPACE
          value: "ghcr.io/samtranbosch"
        - name: DK_ARCH
          value: "arm64"
        - name: DK_CONTAINER_ROOT
          value: "/app/.dk/"
        - name: KUBECONFIG
          value: "/root/.kube/config"
        volumeMounts:
        - name: dk-home
          mountPath: /app/.dk
        - name: x11-unix
          mountPath: /tmp/.X11-unix
        - name: dri
          mountPath: /dev/dri
        - name: kubectl-binary
          mountPath: /usr/local/bin/kubectl
          readOnly: true
        - name: kube-config
          mountPath: /root/.kube/config
          readOnly: true
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: docker-binary
          mountPath: /usr/bin/docker
          readOnly: true
