# Copyright (c) 2025 Eclipse Foundation.
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: MIT

name: Build dreampack-HVAC-app Docker Image
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'qm-apps/dreampack-HVAC-app/**'
      - '.github/workflows/build-dreampack-hvac-app.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        id: docker_login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set TAG variable
        id: vars
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          TAG="${SHORT_SHA}-${BRANCH_NAME}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "TAG=$TAG"  # output for debug
          echo "::set-output name=TAG::$TAG"  # deprecated but kept for backward compatibility

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ./qm-apps/dreampack-HVAC-app
          file: ./qm-apps/dreampack-HVAC-app/app/Dockerfile
          push: ${{ steps.docker_login.outcome == 'success' }}
          tags: |
            ghcr.io/${{ env.OWNER }}/dk_app_dreampack_hvac:${{ env.TAG }}
            ghcr.io/${{ env.OWNER }}/dk_app_dreampack_hvac:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
          # caching   scope dk_app_dreampack_hvac
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to:   type=gha,scope=${{ github.workflow }},mode=max
